"""empty message

Revision ID: 30a833e98c31
Revises: 341f66e9844f
Create Date: 2021-06-24 14:02:14.964063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30a833e98c31'
down_revision = '341f66e9844f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'id')
    # ### end Alembic commands ###
