"""empty message

Revision ID: 341f66e9844f
Revises: 9bd0f21f4147
Create Date: 2021-06-22 12:33:48.386255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '341f66e9844f'
down_revision = '9bd0f21f4147'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('year', sa.String(length=150), nullable=True))
    op.add_column('game', sa.Column('designer', sa.String(length=150), nullable=True))
    op.add_column('game', sa.Column('genre', sa.String(length=150), nullable=True))
    op.drop_column('game', 'year_published')
    op.drop_column('game', 'designer_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('designer_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('game', sa.Column('year_published', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.drop_column('game', 'genre')
    op.drop_column('game', 'designer')
    op.drop_column('game', 'year')
    # ### end Alembic commands ###
