"""empty message

Revision ID: 3583e792f74d
Revises: 95ccd97f4a28
Create Date: 2021-06-20 12:39:30.696350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3583e792f74d'
down_revision = '95ccd97f4a28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_email_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_email_key', 'user', ['email'])
    # ### end Alembic commands ###
