"""empty message

Revision ID: 9bd0f21f4147
Revises: 2c0809f33536
Create Date: 2021-06-21 18:30:02.196202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bd0f21f4147'
down_revision = '2c0809f33536'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('year_published', sa.String(length=150), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('designer_name', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game')
    # ### end Alembic commands ###
